Repository dermotduffy/advanced-camera-card, pull requests merged in 2022-07, with the labels that each got.

#748 Don't show star icon for recordings
  src/components/thumbnail.ts
Labels: bug

#749 Bump version to 4.0.0-rc.2
  package.json
Labels: build

#753 Allow finer grained selection of thumbnail controls
  .vscode/i18n-ally-reviews.yml
  README.md
  src/components/gallery.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/config-mgmt.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
  src/types.ts
Labels: enhancement

#754 Vertically center the progress indicator
  src/scss/live-jsmpeg.scss
  src/scss/message.scss
Labels: style

#757 Add missing pt-br translations
  .vscode/i18n-ally-reviews.yml
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
Labels: enhancement

#767 Complete carousel code refactor
  README.md
  package.json
  src/components/carousel.ts
  src/components/drawer.ts
  src/components/embla-plugins/automedia.ts
  src/components/embla-plugins/lazyload.ts
  src/components/image.ts
  src/components/live.ts
  src/components/media-carousel.ts
  src/components/surround-thumbnails.ts
  src/components/thumbnail-carousel.ts
  src/components/viewer.ts
  src/scss/carousel.scss
  src/scss/live-carousel.scss
  src/scss/media-carousel.scss
  src/scss/next-previous-control.scss
  src/scss/thumbnail-carousel.scss
  src/scss/thumbnail-feature-event.scss
  src/scss/viewer-carousel.scss
  yarn.lock
Labels: refactoring

#768 Use a higher port number for devcontainer rollup
  .devcontainer/devcontainer.json
  .devcontainer/preconfig/.storage/lovelace_resources
  rollup.config.js
Labels: testing

#769 Various documentation improvements
  README.md
Labels: documentation

#770 Move scan mode pulsing border to the outer ha-card
  src/card.ts
  src/scss/card.scss
Labels: style

#771 Allow custom action events (e.g. browser_mod)
  README.md
  src/card.ts
  src/types.ts
Labels: enhancement

#773 Rework the error message when entity is unavailable
  .vscode/i18n-ally-reviews.yml
  src/card.ts
  src/components/live.ts
  src/components/message.ts
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
Labels: style

#774 Restore correct image after browser tab becomes visible
  src/components/image.ts
Labels: bug

#776 Fix carousel forgetting its position in certain circumstances.
  src/components/carousel.ts
  src/components/live.ts
Labels: bug
