Repository dermotduffy/advanced-camera-card, pull requests merged in 2022-03, with the labels that each got.

#435 Bump version to v3.0.0-rc.2
  package.json
  src/const.ts
Labels: build

#440 Avoid submenu exception on HA restart
  src/common.ts
Labels: bug

#441 Don't allow the JSMPEG player to internally reconnect causing auth errors
  src/components/live.ts
Labels: bug

#443 Upload frigate-hass-card artifact on pull request
  .github/workflows/build.yml
Labels: build

#445 Don't use discriminatedUnion for picture elements
  src/types.ts
Labels: bug

#434 Prevent old HA state from using an old image access token
  src/cached-value-controller.ts
  src/common.ts
  src/components/image.ts
  src/editor.ts
Labels: bug

#450 Show an error message / stock image (depending) on image load error
  src/components/image.ts
  src/localize/languages/en.json
Labels: enhancement

#461 Fix menu rendering placement
  src/action-handler-directive.ts
  src/components/submenu.ts
  src/scss/card.scss
  src/scss/menu.scss
  src/scss/submenu.scss
Labels: bug

#462 Bump version to v3.0.0
  package.json
  src/const.ts
Labels: build

#463 Require HA 2022.3.0 (for editor components)
  hacs.json
Labels: build

#464 Add workaround to README for Safari video controls progress bar
  README.md
Labels: documentation

#488 Don't restrict release drafter to main branch
  .github/workflows/release-drafter.yml
Labels: build
