Repository dermotduffy/advanced-camera-card, pull requests merged in 2022-08, with the labels that each got.

#784 Add Italian language translations
  src/localize/languages/it.json
  src/localize/localize.ts
Labels: enhancement

#785 Embed thumbnails to take advantage of cache
  src/components/thumbnail.ts
Labels: performance

#787 Fetch thumbnails for next/previous controls.
  src/components/live.ts
  src/components/next-prev-control.ts
  src/components/thumbnail.ts
  src/components/viewer.ts
  src/utils/thumbnail.ts
Labels: bug

#788 Reduce boilerplate associated with lit tasks
  src/components/live.ts
  src/components/next-prev-control.ts
  src/components/thumbnail.ts
  src/components/viewer.ts
  src/utils/task.ts
  src/utils/thumbnail.ts
Labels: refactoring

#791 Allow elements to be hidden when media is not yet loaded
  README.md
  src/card-condition.ts
  src/card.ts
  src/components/live.ts
  src/components/media-carousel.ts
  src/components/surround-thumbnails.ts
  src/components/thumbnail.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/declarations.d.ts
  src/types.ts
  src/view.ts
Labels: enhancement, breaking

#793 Show still images during live camera load
  .vscode/i18n-ally-reviews.yml
  README.md
  src/card.ts
  src/components/live.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/scss/live-provider.scss
  src/types.ts
Labels: enhancement

#794 Refactor media load events to add unload support
  src/card.ts
  src/components/live.ts
  src/components/media-carousel.ts
  src/components/viewer.ts
  src/types.ts
  src/utils/media-info.ts
  src/view.ts
Labels: bug, refactoring

#795 Fix issue with image timers being created recursively
  src/cached-value-controller.ts
  src/components/image.ts
Labels: bug

#796 Update homeAssistantWSRequest to accept passthrough JSON
  src/utils/frigate.ts
  src/utils/ha/index.ts
Labels: performance

#800 Add ability to change media layout
  .vscode/i18n-ally-reviews.yml
  README.md
  src/components/image.ts
  src/components/live.ts
  src/components/viewer.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/scss/const.scss
  src/scss/editor.scss
  src/scss/image.scss
  src/scss/live-ha-components.scss
  src/scss/live-jsmpeg.scss
  src/scss/live-webrtc.scss
  src/scss/media-layout.scss
  src/scss/viewer-carousel.scss
  src/types.ts
  src/utils/media-info.ts
  src/utils/media-layout.ts
Labels: enhancement

#803 Drawer handle shouldn't activate card actions
  src/components/drawer.ts
Labels: bug

#804 Fix drawer open bug in iOS Safari
  src/components/drawer.ts
  src/components/timeline.ts
  src/utils/basic.ts
Labels: bug
