Repository dermotduffy/advanced-camera-card, pull requests merged in 2022-06, with the labels that each got.

#622 Fix menu rounded corners
  src/scss/menu.scss
Labels: bug

#619 Add recording support
  README.md
  images/dark-mode.gif
  images/recording-seek-all-cameras.gif
  images/recording-seek.gif
  src/card.ts
  src/components/elements.ts
  src/components/gallery.ts
  src/components/live.ts
  src/components/message.ts
  src/components/surround-thumbnails.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/config-mgmt.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/pt_br.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/scss/carousel.scss
  src/scss/const.scss
  src/scss/gallery.scss
  src/scss/media-carousel.scss
  src/scss/message.scss
  src/scss/next-previous-control.scss
  src/scss/thumbnail-carousel.scss
  src/scss/thumbnail-details.scss
  src/scss/thumbnail-feature-event.scss
  src/scss/thumbnail-feature-recording.scss
  src/scss/thumbnail.scss
  src/scss/timeline-core.scss
  src/types.ts
  src/utils/frigate.ts
  src/utils/ha/browse-media.ts
  src/utils/ha/index.ts
  src/view.ts
Labels: enhancement

#627 Don't use wheel plugin when there's only one media item
  src/components/carousel.ts
  src/components/live.ts
  src/components/thumbnail-carousel.ts
  src/components/viewer.ts
Labels: bug

#628 Open/close the drawer automatically for mouse users
  src/components/drawer.ts
Labels: enhancement

#629 Add scan mode untrigger timer
  README.md
  src/card.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/types.ts
Labels: enhancement

#630 Show thumbnail drawer by default in live and media viewer views
  src/types.ts
Labels: style

#631 Minor style changes to gallery
  src/scss/gallery.scss
  src/scss/thumbnail.scss
Labels: style

#632 Bump version to v4.0.0-rc.1 in preparation
  package.json
  src/const.ts
Labels: build

#634 Add a way to get diagnostics for issue reports.
  src/card.ts
  src/components/message.ts
  src/localize/languages/en.json
  src/scss/message.scss
  src/types.ts
  src/utils/ha/device-registry.ts
Labels: enhancement

#635 Fix message color
  README.md
  src/scss/message.scss
Labels: style

#637 Update deps en masse
  .github/workflows/build.yml
  .github/workflows/release.yml
  README.md
  package.json
  src/components/drawer.ts
  yarn.lock
Labels: build

#638 For now remove dependabot for node packages
  .github/dependabot.yml
Labels: build

#639 Upgrade dependencies with major version differences.
  package.json
  yarn.lock
Labels: build

#640 Center text on the recording thumbnail feature item
  src/scss/thumbnail-feature-recording.scss
Labels: style

#650 Improve editor submenu styling
  src/editor.ts
  src/scss/editor.scss
Labels: style

#655 Add a new convenience option for a camera to depend on all others
  README.md
  src/card.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/types.ts
  src/utils/ha/browse-media.ts
Labels: enhancement

#657 Add a note that manual menu/submenu positioning is not supported.
  README.md
Labels: documentation

#656 Break out triggers into their own configuration section
  README.md
  src/card.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/scss/editor.scss
  src/types.ts
Labels: refactoring

#658 Change configuration path for Frigate options
  README.md
  src/card.ts
  src/components/live.ts
  src/components/menu.ts
  src/components/timeline.ts
  src/config-mgmt.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/scss/editor.scss
  src/types.ts
  src/utils/camera.ts
  src/utils/frigate.ts
  src/utils/ha/browse-media.ts
Labels: breaking

#659 Add controls to a submenu in the editor to make it less busy
  src/editor.ts
  src/localize/languages/en.json
  src/scss/editor.scss
Labels: style

#660 Fix downloads from the timeline
  src/card.ts
  src/types.ts
Labels: bug

#662 Small editor spacing fix
  src/scss/editor.scss
Labels: style

#664 Change styling when recordings are disabled
  src/components/timeline.ts
  src/scss/timeline-core.scss
Labels: style

#665 Fix image button upgrade
  src/config-mgmt.ts
Labels: bug

#669 Fix issue causing image to refetch too frequently
  src/components/image.ts
Labels: bug

#672 Deduplicate Frigate cameras on the timeline (support multiple live providers)
  src/components/timeline.ts
  src/utils/frigate.ts
Labels: enhancement

#673 Allow the image view to trigger a card resize
  src/card.ts
  src/components/elements.ts
  src/view.ts
Labels: bug

#674 Don't load cameras where there's an error message being displayed
  src/card.ts
Labels: bug

#675 Use a proper ISO8601 formatted date to fix the timeline in Safari/iOS.
  src/utils/frigate.ts
Labels: bug

#677 Include the language in diagnostics output
  src/card.ts
  src/localize/localize.ts
Labels: enhancement

#681 Add browser to diagnostics
  src/card.ts
Labels: enhancement

#682 Fall back to live if the user changes view from recordings.
  src/card.ts
  src/types.ts
  src/view.ts
Labels: bug

#684 Fix state color in submenu items
  src/card.ts
  src/components/submenu.ts
  src/types.ts
Labels: bug

#688 Fix webrtc card style issue in Safari
  src/components/live.ts
  src/scss/live-webrtc.scss
Labels: style

#676 Fix malformed live carousel bug that some users experience
  src/components/media-carousel.ts
Labels: bug

#685 Don't re-render the whole card for conditionState
  src/card.ts
  src/components/elements.ts
  src/components/live.ts
Labels: performance

#683 Allow the provided URL to be used as the stock loading image.
  README.md
  src/components/image.ts
  src/scss/card.scss
Labels: enhancement

#690 Configure VS Code debug and tasks
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  rollup.config.js
  tsconfig.json
Labels: build

#692 Fit image content to parent size.
  src/patches/ha-camera-stream.ts
Labels: style

#698 Don't spam the log if the sensor entity lookup fails
  src/card.ts
Labels: bug

#693 Add docker to the devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/initialize.sh
  docker-compose.yml
Labels: testing

#700 Clean lit-plugin warnings
  .devcontainer/initialize.sh
  package.json
  src/action-handler-directive.ts
  src/card.ts
  src/components/drawer.ts
  src/components/elements.ts
  src/components/gallery.ts
  src/components/image.ts
  src/components/live.ts
  src/components/media-carousel.ts
  src/components/menu.ts
  src/components/message.ts
  src/components/next-prev-control.ts
  src/components/submenu.ts
  src/components/surround-thumbnails.ts
  src/components/surround.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/components/timeline.ts
  src/components/title-control.ts
  src/components/viewer.ts
  src/editor.ts
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/types.ts
  tsconfig.json
  yarn.lock
Labels: refactoring

#702 Option overrides are always optional
  src/types.ts
Labels: bug

#704 Make error handling and console logging consistent
  src/card.ts
  src/components/live.ts
  src/components/timeline.ts
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
  src/types.ts
  src/utils/basic.ts
  src/utils/frigate.ts
  src/utils/ha/entity-registry.ts
  src/utils/ha/index.ts
  src/utils/ha/resolved-media.ts
Labels: refactoring

#705 Don't execute card actions when timeline is dragged
  src/components/timeline.ts
Labels: bug

#706 Prefetch events from a larger range than the timeline shows
  src/components/timeline.ts
Labels: performance

#694 Add Dev Container section on README
  README.md
Labels: documentation

#707 Change screenshots to use release branch for serving in HACS
  README.md
Labels: documentation

#713 Improve disconnection/reconnection UX
  .vscode/i18n-ally-reviews.yml
  .vscode/settings.json
  src/card.ts
  src/components/message.ts
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
  src/scss/message.scss
  src/types.ts
Labels: enhancement

#715 Messages should respect static dimensions
  src/card.ts
  src/components/image.ts
  src/components/live.ts
  src/components/message.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/scss/message.scss
  src/types.ts
  src/utils/ha/browse-media.ts
Labels: bug

#716 Hide elements when messages are displayed.
  src/card.ts
Labels: bug

#718 No longer support actions on timeline view.
  README.md
  src/action-handler-directive.ts
  src/card.ts
  src/components/timeline.ts
  src/types.ts
Labels: removal

#719 Don't support card-wide actions when a message is displayed
  README.md
  src/card.ts
Labels: removal

#724 Various timeline fixes for Safari
  src/card.ts
  src/components/timeline.ts
  src/scss/card.scss
  src/scss/timeline-core.scss
Labels: bug

#725 Cause a refresh when scan mode untriggers
  src/card.ts
Labels: bug

#727 Fix curved borders on Safari
  src/scss/card.scss
Labels: style

#728 Fix gallery sizing in Safari
  src/scss/card.scss
  src/scss/gallery.scss
  src/scss/live-webrtc.scss
Labels: style

#730 Move elements to outside main pane.
  src/card.ts
Labels: bug

#736 Various style and behavior fixes (background colors, scrolling reset)
  src/card.ts
  src/scss/card.scss
  src/scss/elements.scss
  src/scss/gallery.scss
  src/scss/live-webrtc.scss
  src/scss/message.scss
Labels: style

#737 Fix Safari live camera loop bug
  src/components/media-carousel.ts
Labels: bug

#738 Change effect to scale whole thumbnail
  src/scss/gallery.scss
  src/scss/thumbnail-carousel.scss
  src/scss/thumbnail-feature-event.scss
  src/scss/thumbnail-feature-recording.scss
  src/scss/thumbnail.scss
Labels: style

#739 Fix thumbnail proportions in Safari
  src/scss/card.scss
  src/scss/thumbnail-feature-event.scss
Labels: bug

#740 Add v4 troubleshooting entry.
  README.md
Labels: documentation

#742 Fix the hover menu styling (again)
  src/card.ts
Labels: bug

#744 Add event starring from the card
  .vscode/i18n-ally-reviews.yml
  README.md
  images/star.gif
  src/components/gallery.ts
  src/components/live.ts
  src/components/surround-thumbnails.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
  src/localize/localize.ts
  src/scss/thumbnail.scss
  src/utils/frigate.ts
Labels: enhancement

#746 Convert recordings to websocket.
  src/localize/languages/en.json
  src/localize/languages/pt-BR.json
  src/utils/frigate.ts
  src/utils/ha/index.ts
Labels: refactoring
