Repository dermotduffy/advanced-camera-card, pull requests merged in 2022-10, with the labels that each got.

#850 Make the controls section of the editor much cleaner
  README.md
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/localize.ts
  src/scss/editor.scss
Labels: enhancement

#851 Ensure container resizes when parent resizes
  src/components/media-carousel.ts
  src/components/timeline-core.ts
  src/editor.ts
  src/scss/live-webrtc.scss
Labels: bug

#852 Add ability to download recordings
  src/card.ts
Labels: enhancement

#858 Add view / menu button for recordings
  README.md
  src/card.ts
  src/components/gallery.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/components/timeline-core.ts
  src/components/viewer.ts
  src/editor.ts
  src/localize/languages/en.json
  src/scss/thumbnail-feature-recording.scss
  src/types.ts
  src/utils/camera.ts
  src/utils/ha/browse-media.ts
  src/utils/media-to-view.ts
  src/utils/timeline-data-manager.ts
  src/view.ts
Labels: enhancement

#859 Rename TimelineDataManager to DataManager
  src/card.ts
  src/components/gallery.ts
  src/components/live.ts
  src/components/surround.ts
  src/components/timeline-core.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/utils/data-manager.ts
  src/utils/media-to-view.ts
Labels: refactoring

#861 Add `low` performance profile and `image` live provider
  .github/workflows/build.yml
  .github/workflows/release.yml
  README.md
  rollup.config.js
  src/card-condition.ts
  src/card.ts
  src/components/carousel.ts
  src/components/gallery.ts
  src/components/image.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live-jsmpeg.ts
  src/components/live/live-webrtc.ts
  src/components/live/live.ts
  src/components/media-carousel.ts
  src/components/message.ts
  src/components/next-prev-control.ts
  src/components/surround.ts
  src/components/thumbnail.ts
  src/components/timeline-core.ts
  src/components/viewer.ts
  src/config-mgmt.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/localize.ts
  src/performance.ts
  src/scss/drawer-inject.scss
  src/scss/editor.scss
  src/scss/gallery.scss
  src/scss/message.scss
  src/scss/next-previous-control.scss
  src/scss/thumbnail-feature-event.scss
  src/scss/thumbnail-feature-recording.scss
  src/scss/thumbnail.scss
  src/scss/timeline-core.scss
  src/types.ts
  src/utils/basic.ts
  src/utils/data-manager.ts
  src/utils/ha/browse-media.ts
  src/utils/media-to-view.ts
  src/utils/task.ts
  src/view.ts
  tsconfig.json
Labels: performance

#862 Use lodash cloneDeep and generate facade chunk
  rollup.config.js
  src/card-condition.ts
  src/config-mgmt.ts
  src/editor.ts
Labels: bug

#863 Hide video controls briefly on media load for cleaner look
  src/components/live/live-webrtc.ts
  src/patches/ha-hls-player.ts
  src/utils/media.ts
Labels: style

#864 Add a `hover-card` menu style
  README.md
  rollup.config.js
  src/editor.ts
  src/localize/languages/en.json
  src/scss/card.scss
  src/scss/menu.scss
  src/types.ts
Labels: style

#866 Add media query support (conditions based on device properties such as orientation or viewport width)
  README.md
  src/card-condition.ts
  src/card.ts
  src/types.ts
Labels: enhancement

#867 Add hiding controls to native webrtc player (oops)
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
Labels: bug

#868 Optionally prevent playing a clip on snapshot click
  README.md
  src/components/viewer.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/performance.ts
  src/types.ts
Labels: enhancement

#869 Rename `mediaLoaded` to `media_loaded`
  README.md
  src/card-condition.ts
  src/card.ts
  src/config-mgmt.ts
  src/const.ts
  src/types.ts
Labels: breaking

#870 Expand the timeline to 100% height in panel mode
  src/card.ts
  src/scss/card.scss
  src/scss/thumbnail-feature-event.scss
  src/scss/timeline-core.scss
  src/utils/ha/index.ts
Labels: bug

#875 Fix carousel previous/next controls not showing
  src/components/carousel.ts
  src/components/media-carousel.ts
  src/components/viewer.ts
Labels: bug

#882 Fix media player icons
  src/utils/icons/domain-icon.ts
Labels: bug
