Repository dermotduffy/advanced-camera-card, pull requests merged in 2022-05, with the labels that each got.

#530 Allow use of HA state in Frigate Card Conditions (e.g. for use in configuration overrides)
  README.md
  src/card-condition.ts
  src/card.ts
  src/components/elements.ts
  src/components/live.ts
  src/types.ts
Labels: enhancement

#533 Allow view to be overridden (e.g. change default card view based on HA state)
  README.md
  src/card.ts
  src/types.ts
Labels: enhancement

#534 Remove attempt to serve in prod env
  rollup.config.js
Labels: bug

#535 Add native cast/media_player support
  README.md
  src/card.ts
  src/common.ts
  src/components/submenu.ts
  src/editor.ts
  src/localize/languages/en.json
  src/types.ts
Labels: enhancement

#539 Import full set of entity icons to fix 'checkmark' issue
  src/common.ts
  src/icons/LICENSE
  src/icons/README.md
  src/icons/alarm-panel-icon.ts
  src/icons/binary-sensor-icon.ts
  src/icons/cover-icon.ts
  src/icons/domain-icon.ts
  src/icons/sensor-icon.ts
  src/icons/state-icon.ts
  src/icons/update.ts
Labels: bug

#541 Add new lazily unload criteria
  README.md
  src/components/embla-plugins/lazyload.ts
  src/components/live.ts
  src/components/viewer.ts
  src/config-mgmt.ts
  src/editor.ts
  src/localize/languages/en.json
  src/types.ts
Labels: enhancement, breaking

#544 Implement `auto_play`, `auto_pause`, `auto_mute` and `auto_unmute`
  README.md
  rollup.config.js
  src/components/embla-plugins/automedia.ts
  src/components/live.ts
  src/components/surround-thumbnails.ts
  src/components/viewer.ts
  src/config-mgmt.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/types.ts
Labels: enhancement, breaking

#547 Add native select/input_select entity support for submenus
  README.md
  rollup.config.js
  src/components/elements.ts
  src/components/menu.ts
  src/components/submenu.ts
  src/types.ts
Labels: enhancement

#548 For configuration consistency: Change menu subitem 'disabled' => 'enabled'
  README.md
  src/components/submenu.ts
  src/types.ts
Labels: style

#550 Use `cloneDeep` instead of JSON parsing
  src/config-mgmt.ts
Labels: performance

#551 Change the hover menu to only show up when the mouse is over the menu
  README.md
  src/scss/card.scss
Labels: style

#552 Remove usage of deprecated attribute
  src/action-handler-directive.ts
Labels: refactoring

#559 Don't fetch thumbnails on preloaded camera in the background
  src/components/live.ts
  src/components/surround-thumbnails.ts
  src/types.ts
Labels: bug

#560 Add fully expanded configuration reference
  README.md
Labels: documentation

#561 Small README fixes
  README.md
Labels: documentation

#562 Fix live view for non-Frigate cameras
  src/components/live.ts
Labels: bug

#563 Don't allow elements to overflow
  src/scss/elements.scss
Labels: bug

#564 Ensure a refreshed elements config causes the elements to update
  src/components/elements.ts
Labels: bug

#565 Only show media players capable of casting
  src/card.ts
  src/const.ts
Labels: enhancement

#569 Fix card breakage on Nest hub devices
  src/localize/localize.ts
Labels: bug

#572 Improve the Frigate-card-on-Chromecast experience
  src/card.ts
  src/common.ts
  src/components/drawer.ts
  src/components/live.ts
  src/components/thumbnail-carousel.ts
  src/components/viewer.ts
  src/editor.ts
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/scss/drawer-inject.scss
  src/scss/drawer.scss
  src/types.ts
Labels: enhancement

#574 Fix snapshots on Chromecast
  src/components/viewer.ts
Labels: bug

#575 Don't show camera names in the gallery if there's only 1 camera
  src/browse-media-util.ts
Labels: style

#577 Improve timeline behavior with non-Frigate cameras
  src/card.ts
  src/components/timeline.ts
  src/localize/languages/en.json
Labels: enhancement

#578 Prevent drawer from being wider than the card
  src/scss/drawer-inject.scss
Labels: bug

#584 Refactor `common.js` into multiple files
  src/action-handler-directive.ts
  src/browse-media-util.ts
  src/card.ts
  src/common.ts
  src/components/carousel.ts
  src/components/elements.ts
  src/components/gallery.ts
  src/components/image.ts
  src/components/live.ts
  src/components/media-carousel.ts
  src/components/menu.ts
  src/components/message.ts
  src/components/submenu.ts
  src/components/surround-thumbnails.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/editor.ts
  src/icons/alarm-panel-icon.ts
  src/icons/binary-sensor-icon.ts
  src/icons/cover-icon.ts
  src/icons/domain-icon.ts
  src/icons/sensor-icon.ts
  src/icons/state-icon.ts
  src/icons/update.ts
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/resolved-media.ts
  src/types.ts
  src/utils/action.ts
  src/utils/basic.ts
  src/utils/camera.ts
  src/utils/ha/browse-media.ts
  src/utils/ha/index.ts
  src/utils/ha/update.ts
  src/utils/icons/LICENSE
  src/utils/icons/README.md
  src/utils/icons/alarm-panel-icon.ts
  src/utils/icons/binary-sensor-icon.ts
  src/utils/icons/cover-icon.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/sensor-icon.ts
  src/utils/icons/state-icon.ts
  src/utils/media-info.ts
  src/utils/resolved-media.ts
  src/utils/zod.ts
  src/view.ts
Labels: refactoring

#585 Fix menu alignment for the `outside` menu style
  README.md
  src/scss/menu.scss
Labels: bug

#587 Reduce thumbnail fetch frequency to prevent Frigate request timeouts
  src/components/surround-thumbnails.ts
Labels: bug

#588 Update installation instructions for Lovelace storage mode
  README.md
Labels: documentation

#592 Fix malformed Safari live carousel
  src/components/live.ts
  src/components/media-carousel.ts
  src/components/viewer.ts
Labels: bug

#593 Add missing cameras button to editor
  src/editor.ts
  src/localize/languages/en.json
Labels: bug

#603 Fix compatability with Frigate 0.11
  src/types.ts
  src/utils/ha/index.ts
Labels: bug

#606 Add Scan mode (Have your card follow the action!)
  README.md
  src/card.ts
  src/components/image.ts
  src/components/live.ts
  src/components/submenu.ts
  src/components/viewer.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/scss/card.scss
  src/scss/editor.scss
  src/types.ts
  src/utils/ha/entity-registry.ts
  src/utils/ha/index.ts
  src/utils/ha/resolved-media.ts
Labels: enhancement

#610 Add new screenshots
  README.md
  images/cast-your-events.gif
  images/scan-mode.gif
  images/submenu-select.gif
  images/thumbnails-in-drawer.gif
  images/timeline.gif
Labels: documentation

#611 Refactor aspect-ratio logic
  src/card.ts
  src/scss/card.scss
Labels: refactoring

#612 Add documentation on Chromecasting
  README.md
  images/card-on-nest-hub.jpg
Labels: documentation
