Repository dermotduffy/advanced-camera-card, pull requests merged in 2023-05, with the labels that each got.

#1134 Initialize media players if they have not been initialized.
  README.md
  src/card.ts
Labels: bug

#1141 Add support for in-card automation
  README.md
  src/automations.ts
  src/card-condition.ts
  src/card.ts
  src/components/elements.ts
  src/components/live/live.ts
  src/components/views.ts
  src/conditions.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/types.ts
  src/utils/action.ts
  src/utils/camera.ts
  src/utils/substream.ts
  tests/automations.test.ts
  tests/camera-manager/engine-factory.test.ts
  tests/conditions.test.ts
  tests/test-utils.ts
  tests/utils/action.test.ts
  tests/utils/camera.test.ts
  tests/utils/debug.test.ts
  tests/utils/substream.test.ts
Labels: enhancement

#1142 Fix Frigate event schema break (`top_score` === `null`)
  src/camera-manager/frigate/types.ts
  src/camera-manager/frigate/util.ts
  tests/camera-manager/frigate/util.test.ts
  tests/test-utils.ts
Labels: bug

#1143 Update installation instructions for manual installation
  README.md
Labels: documentation

#1144 Show different mouse cursor when zoomed in
  src/components/zoomer.ts
  src/utils/zoom/zoom.ts
Labels: enhancement

#1145 Add support for disabling zoom
  README.md
  src/components/image.ts
  src/components/live/live-image.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/types.ts
Labels: enhancement

#1146 Maintain substream selections during view cycling
  src/view/view.ts
  tests/view/view.test.ts
Labels: bug

#1147 Implement `momentary` and `toggle` microphone button types
  src/card.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/types.ts
  src/utils/microphone.ts
Labels: enhancement

#1149 Add option to have microphone `always_connected`
  README.md
  src/card.ts
  src/components/live/live-go2rtc.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/types.ts
  tests/utils/debug.test.ts
  tests/utils/microphone.test.ts
Labels: enhancement

#1150 Only show the microphone button if the media that is loaded supports 2-way audio
  README.md
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/types.ts
  src/card.ts
  src/components/image.ts
  src/components/live/live-go2rtc.ts
  src/components/live/live-image.ts
  src/components/live/live-jsmpeg.ts
  src/components/live/live-webrtc-card.ts
  src/components/viewer.ts
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/types.ts
  src/utils/media-info.ts
Labels: enhancement

#1153 Fix typo in automations documentation
  README.md
Labels: documentation

#1157 Add {play/pause/mute/unmute} Frigate card commands
  src/cached-value-controller.ts
  src/card.ts
  src/components/image.ts
  src/components/live/live-go2rtc.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live-jsmpeg.ts
  src/components/live/live-webrtc-card.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/types.ts
  src/utils/audio.ts
  src/utils/media-info.ts
  tests/cached-value-controller.test.ts
  tests/utils/audio.test.ts
Labels: enhancement

#1159 Fix small typo
  README.md
Labels: documentation

#1161 Allow default media controls to be hidden
  README.md
  src/components/live/go2rtc/README.md
  src/components/live/go2rtc/video-rtc.d.ts
  src/components/live/go2rtc/video-rtc.js
  src/components/live/live-go2rtc.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live-jsmpeg.ts
  src/components/live/live-webrtc-card.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/const.ts
  src/editor.ts
  src/external/go2rtc/README.md
  src/external/go2rtc/video-rtc.js
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/types.ts
Labels: enhancement

#1162 Dispatch load events for mp4/mjpeg from go2rtc
  src/components/live/go2rtc/video-rtc.js
Labels: bug

#1164 Add additional cache reset troubleshooting tip
  README.md
Labels: documentation

#1166 Bump version to v5.1.0.
  package.json
Labels: build

#1167 Merge minor documentation changes from `main` into `dev`
  README.md
Labels: documentation

#1168 Add screenshots for v5.1.0
  README.md
  images/microphone.gif
  images/native-media-control.png
  images/zoom.gif
Labels: documentation

#1169 Merge screenshots into `main`
  README.md
  images/microphone.gif
  images/native-media-control.png
  images/zoom.gif
Labels: documentation

#1170 Refactor timers into a simple tested object
  src/action-handler-directive.ts
  src/cached-value-controller.ts
  src/card.ts
  src/components/live/live-jsmpeg.ts
  src/components/media-carousel.ts
  src/utils/media.ts
  src/utils/microphone.ts
  src/utils/timer.ts
  tests/utils/timer.test.ts
Labels: refactoring

#1172 Fix overrides bug caused by incorrect initial state
  package.json
  src/card.ts
Labels: bug

#1173 Merge fix in `main` back into `dev`
  package.json
  src/card.ts
Labels: build

#1175 Refactor menu button logic out of main card
  src/card.ts
  src/components/menu.ts
  src/const.ts
  src/utils/icons/domain-icon.ts
  src/utils/menu-controller.ts
  tests/test-utils.ts
  tests/utils/camera.test.ts
  tests/utils/menu-controller.test.ts
  tests/utils/substream.test.ts
  tests/view/view.test.ts
Labels: refactoring

#1176 Break parser error handling out of main card
  src/card.ts
  src/utils/zod.ts
  tests/utils/zod.test.ts
Labels: refactoring

#1177 Refactor media info handling into a controller
  src/card.ts
  src/utils/media-info-controller.ts
  src/utils/media-info.ts
  tests/utils/media-info-controller.test.ts
  tests/utils/media-info.test.ts
Labels: refactoring

#1179 Fix zoom in Firefox and Safari
  src/components/live/go2rtc/video-rtc.js
  src/components/live/live-go2rtc.ts
  src/components/live/live-webrtc-card.ts
  src/components/viewer.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/utils/media.ts
  src/utils/zoom/zoom.ts
  tests/utils/media.test.ts
  tests/utils/zoom.test.ts
Labels: bug

#1182 Add additional `inlang` documentation
  README.md
  inlang.config.js
Labels: documentation
