Repository dermotduffy/advanced-camera-card, pull requests merged in 2023-10, with the labels that each got.

#1275 fix: update inlang settings
  .vscode/extensions.json
  inlang.config.js
  project.inlang.json
Labels: bug

#1281 Fix query string handling for navigation calls
  src/card-controller/query-string-manager.ts
Labels: bug

#1282 Safely handle invalid null `hass` objects
  src/card-controller/hass-manager.ts
  src/card-controller/message-manager.ts
  src/utils/ha/index.ts
  tests/card-controller/hass-manager.test.ts
  tests/card-controller/message-manager.test.ts
  tests/utils/ha/index.test.ts
Labels: bug

#1283 Deal with camera unavailability in a cleaner way
  project.inlang.json
  src/card-controller/view-manager.ts
  src/card.ts
  src/components-lib/cached-value-controller.ts
  src/components-lib/media-grid-controller.ts
  src/components-lib/menu-controller.ts
  src/components-lib/timeline-source.ts
  src/components-lib/zoom-controller.ts
  src/components/image.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live.ts
  src/components/media-grid.ts
  src/components/message.ts
  src/components/timeline-core.ts
  src/components/viewer.ts
  src/components/zoomer.ts
  src/utils/embla/reinit-controller.ts
  src/utils/get-state-obj.ts
  tests/cached-value-controller.test.ts
  tests/components-lib/media-grid-controller.test.ts
  tests/components-lib/menu-controller.test.ts
  tests/components-lib/zoom-controller.test.ts
  tests/utils/get-state-obj.ts
Labels: bug

#1284 Clarify installation instructions
  README.md
Labels: documentation

#1287 Fix issue causing carousel to not correctly scroll
  package.json
  src/components/carousel.ts
  yarn.lock
Labels: bug

#1290 Add watermark to temporary image on live view
  README.md
  src/components/live/live-image.ts
  src/components/live/live.ts
  src/components/title-control.ts
  src/components/viewer.ts
  src/scss/live-image.scss
  src/scss/title-control.scss
Labels: enhancement

#1291 Add support for go2rtc to non-Frigate cameras
  README.md
  src/camera-manager/engine-factory.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/motioneye/engine-motioneye.ts
  src/camera-manager/utils.ts
  src/components-lib/timeline-source.ts
  src/components/live/live-go2rtc.ts
  src/components/timeline-core.ts
  src/config/types.ts
  tests/camera-manager/frigate/engine-frigate.test.ts
  tests/camera-manager/generic/engine-generic.test.ts
  tests/camera-manager/utils.test.ts
  tests/config/types.test.ts
Labels: enhancement

#1292 Minor README improvement for go2rtc `url` parameter
  README.md
Labels: documentation

#1293 Improve engine identification and id generation
  src/camera-manager/engine-factory.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/components-lib/menu-controller.ts
  src/utils/camera.ts
  src/utils/ha/index.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/state-icon.ts
  tests/camera-manager/engine-factory.test.ts
  tests/camera-manager/generic/engine-generic.test.ts
  tests/utils/camera.test.ts
  tests/utils/ha/index.test.ts
Labels: enhancement

#1294 Rename `service_data` to `data` to maintain HA compatibility
  package.json
  src/action-handler-directive.ts
  src/camera-manager/browse-media/engine-browse-media.ts
  src/camera-manager/engine-factory.ts
  src/camera-manager/engine.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/frigate/requests.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/motioneye/engine-motioneye.ts
  src/card-controller/controller.ts
  src/card-controller/triggers-manager.ts
  src/card.ts
  src/components-lib/menu-controller.ts
  src/components/diagnostics.ts
  src/components/elements.ts
  src/components/image.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live-webrtc-card.ts
  src/components/media-filter.ts
  src/components/menu.ts
  src/components/next-prev-control.ts
  src/components/submenu.ts
  src/config-mgmt.ts
  src/config/types.ts
  src/editor.ts
  src/localize/localize.ts
  src/types.ts
  src/utils/action.ts
  src/utils/diagnostics.ts
  src/utils/get-state-obj.ts
  src/utils/ha/browse-media/browse-media-manager.ts
  src/utils/ha/device-registry.ts
  src/utils/ha/entity-registry/index.ts
  src/utils/ha/entity-state-translation.ts
  src/utils/ha/index.ts
  src/utils/ha/resolved-media.ts
  src/utils/icons/domain-icon.ts
  src/utils/icons/sensor-icon.ts
  src/utils/thumbnail.ts
  tests/components-lib/menu-controller.test.ts
  tests/config-mgmt.test.ts
  tests/config/types.test.ts
  tests/utils/action.test.ts
  tests/utils/ha/index.test.ts
  yarn.lock
Labels: bug, breaking

#1296 Add new method of casting that supports low latency live streams
  README.md
  src/card-controller/media-player-manager.ts
  src/card-controller/query-string-manager.ts
  src/card-controller/types.ts
  src/config/types.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  tests/card-controller/media-player-manager.test.ts
  tests/card-controller/query-string-manager.test.ts
Labels: enhancement

#1313 Enforce coverage %
  .github/workflows/build.yml
  .gitignore
  rollup.config.js
  vite.config.ts
Labels: testing
