Repository dermotduffy/advanced-camera-card, pull requests merged in 2023-04, with the labels that each got.

#1042 Minor media player initialization fix
  src/camera-manager/motioneye/engine-motioneye.ts
  src/card.ts
Labels: bug

#1043 Add missing language strings for v5.0.0: `it`
  src/localize/languages/it.json
Labels: bug

#1045 Screenshot URL fix
  README.md
Labels: documentation

#1046 Don't show timeline bar if we cannot seek
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/types.ts
  src/components/timeline-core.ts
Labels: bug

#1047 Add performance profile screenshot
  README.md
  images/performance.png
Labels: documentation

#1049 Fix expanded mode / fullscreen interactions
  src/card.ts
  src/scss/card.scss
Labels: bug

#1050 Fix README build/funding links
  .github/FUNDING.yml
  README.md
Labels: documentation

#1051 Fix sponsor iframe
  README.md
Labels: documentation

#1052 Merge minor main changes back into release branch
  .github/FUNDING.yml
  .github/workflows/labeler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  README.md
Labels: build

#1053 Fix broken language detection
  src/localize/localize.ts
Labels: bug

#1059 Add unittest coverage for engine-factory
  .github/workflows/build.yml
  .gitignore
  .vscode/extensions.json
  package.json
  src/camera-manager/engine-factory.ts
  src/types.ts
  tests/camera-manager/engine-factory.test.ts
  yarn.lock
Labels: testing

#1060 Add tests for camera manager cache
  .vscode/settings.json
  src/camera-manager/cache.ts
  src/camera-manager/frigate/engine-frigate.ts
  tests/camera-manager/cache.test.ts
  tests/camera-manager/engine-factory.test.ts
Labels: testing

#1061 Add camera manager range tests
  src/camera-manager/range.ts
  tests/camera-manager/range.test.ts
Labels: testing

#1063 Zip built files for non-HACS users
  .github/workflows/release.yml
Labels: build

#1067 Improve behavior when timeline items are clicked
  src/components/surround.ts
  src/components/timeline-core.ts
  src/components/timeline.ts
  src/const.ts
  src/types.ts
Labels: bug

#1070 Allow smooth panning between past & present
  src/camera-manager/frigate/media.ts
  src/card.ts
  src/components/live/live-go2rtc.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live-jsmpeg.ts
  src/components/live/live-webrtc-card.ts
  src/components/live/live.ts
  src/components/surround.ts
  src/components/timeline-core.ts
  src/components/timeline.ts
  src/components/viewer.ts
  src/components/views.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/scss/card.scss
  src/scss/live.scss
  src/scss/surround-basic.scss
  src/scss/surround.scss
  src/scss/views.scss
  src/types.ts
  src/utils/media-info.ts
  src/utils/media-to-view.ts
  src/utils/media.ts
  src/view/media.ts
Labels: enhancement

#1071 Sort language JSON
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
Labels: refactoring

#1072 Keep timeline window placement on event click
  src/components/timeline-core.ts
Labels: bug

#1081 Fix issue with media filter and `unconstrained` dimensions
  README.md
  src/card.ts
  src/components/gallery.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/scss/card.scss
  src/scss/gallery-core.scss
  src/scss/gallery.scss
  src/types.ts
Labels: bug

#1086 Add support for new ribbon style timeline
  README.md
  src/components/timeline-core.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/scss/timeline-core.scss
  src/types.ts
  src/utils/basic.ts
  src/utils/media-to-view.ts
  src/utils/timeline-source.ts
  src/view/media.ts
Labels: enhancement

#1087 Add unitests for `basic` support functions
  package.json
  src/utils/basic.ts
  tests/basic.test.ts
  yarn.lock
Labels: testing

#1089 Add label to timeline marker with current time
  src/components/timeline-core.ts
  src/scss/timeline-core.scss
  src/utils/basic.ts
  tests/basic.test.ts
Labels: enhancement

#1091 Fix clicking on timeline recordings
  src/card.ts
  src/components/timeline-core.ts
  src/view/view.ts
Labels: bug

#1092 Add view unittests
  src/view/view.ts
  tests/utils/basic.test.ts
  tests/view/view.test.ts
Labels: testing

#1093 Minor style fixes for timeline/thumbnails
  src/scss/thumbnail-carousel.scss
  src/scss/timeline-core.scss
Labels: bug

#1094 Add screenshot for ribbon timeline
  README.md
  images/ribbon-timeline.png
Labels: documentation

#1095 Bump version to v5.0.0-beta.2
  package.json
Labels: build

#1096 Fix release zipper
  .github/workflows/release.yml
Labels: build

#1097 Second attempt to fix zipper
  .github/workflows/release.yml
Labels: build

#1098 Third attempt to fix zipper
  .github/workflows/release.yml
Labels: build

#1101 Fix screenshot extension
  README.md
Labels: documentation

#1104 Bump version to v5.0.0
  package.json
Labels: build

#1106 Repoint all screenshots to the main branch
  README.md
Labels: documentation

#1109 Add zoom support
  package.json
  src/components/image.ts
  src/components/live/live-go2rtc.ts
  src/components/live/live-ha.ts
  src/components/live/live-image.ts
  src/components/live/live-jsmpeg.ts
  src/components/live/live-webrtc-card.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/components/views.ts
  src/components/zoomer.ts
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/scss/live-provider.scss
  src/types.ts
  src/utils/zoom/zoom.ts
  tests/utils/basic.test.ts
  tests/utils/zoom.test.ts
  yarn.lock
Labels: enhancement

#1125 Add experimental 2-way audio support
  README.md
  src/action-handler-directive.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/types.ts
  src/card.ts
  src/components/live/live-go2rtc.ts
  src/components/live/live.ts
  src/components/views.ts
  src/const.ts
  src/editor.ts
  src/external/go2rtc/video-rtc.d.ts
  src/external/go2rtc/video-rtc.js
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/scss/button.scss
  src/types.ts
  src/utils/microphone.ts
  tests/utils/microphone.test.ts
Labels: enhancement

#1126 Fix incorrect engine detection
  src/camera-manager/engine-factory.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/util.ts
  tests/camera-manager/engine-factory.test.ts
  tests/camera-manager/utils.test.ts
Labels: bug

#1127 Various github workflow fixes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/dependabot.yml
  .github/labels.yml
  .github/workflows/build.yml
Labels: build

#1038 Add language: Portuguese (Portugal)
  src/localize/languages/pt-PT.json
  src/localize/localize.ts
Labels: enhancement
