Repository dermotduffy/advanced-camera-card, pull requests merged in 2023-03, with the labels that each got.

#983 Retire auto-upgrades <= `v3.0.0`
  src/config-mgmt.ts
Labels: performance

#982 Add support for global cameras options
  README.md
  src/camera-manager/manager.ts
  src/card.ts
  src/config-mgmt.ts
  src/const.ts
  src/types.ts
  src/utils/initializer.ts
Labels: bug

#986 Remove unnecessary entity fetches
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/manager.ts
  src/card.ts
  src/utils/ha/entity-registry/cache.ts
  src/utils/ha/entity-registry/index.ts
  src/utils/ha/entity-registry/types.ts
Labels: performance

#985 Fix broken select entity translation labels
  src/card.ts
  src/components/menu.ts
  src/components/submenu.ts
  src/utils/ha/entity-registry/types.ts
  src/utils/ha/entity-state-translation.ts
Labels: bug

#987 Fix `low` performance profile camera defaults
  src/const.ts
  src/performance.ts
Labels: bug

#988 Fix language choice when localStorage language may be unavailable
  src/card.ts
  src/localize/localize.ts
Labels: bug

#989 Fix media player icons not refreshing
  src/card.ts
Labels: bug

#991 Do not show `ha` live provider errors unless they are fatal
  src/patches/ha-hls-player.ts
Labels: bug

#992 Add sub_label ("tags") support
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/frigate/media.ts
  src/camera-manager/frigate/types.ts
  src/camera-manager/manager.ts
  src/camera-manager/types.ts
  src/components/media-filter.ts
  src/components/thumbnail.ts
  src/localize/languages/en.json
  src/view/media.ts
Labels: enhancement

#993 Automatically scroll to a thumbnail in the gallery if you were viewing it in the viewer
  src/card.ts
  src/components/gallery.ts
Labels: enhancement

#997 Add support for 'scroll up refresh' in the gallery
  src/camera-manager/engine.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/types.ts
  src/components/gallery.ts
  src/components/message.ts
  src/components/surround.ts
  src/components/timeline-core.ts
  src/components/viewer.ts
  src/scss/gallery.scss
  src/scss/message.scss
  src/utils/basic.ts
  src/utils/debug.ts
  src/utils/media-to-view.ts
  src/view/media-queries-results.ts
Labels: enhancement

#999 Fix issues on DOM disconnect for certain live providers
  src/components/live/live-go2rtc.ts
  src/components/live/live-webrtc-card.ts
Labels: bug

#1001 Add support for expanding the card without needing fullscreen
  README.md
  package.json
  src/card-condition.ts
  src/card.ts
  src/components/carousel.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/scss/card.scss
  src/types.ts
  yarn.lock
Labels: enhancement

#1002 Fix behavior of expanded mode in certain cases
  README.md
  src/card.ts
  src/scss/card.scss
Labels: bug

#1003 Add support for multiple zones/labels per Frigate camera
  README.md
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/manager.ts
  src/config-mgmt.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/types.ts
Labels: enhancement, breaking

#1005 Add download control to thumbnails
  README.md
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/types.ts
  src/card.ts
  src/components/gallery.ts
  src/components/message.ts
  src/components/thumbnail-carousel.ts
  src/components/thumbnail.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/performance.ts
  src/scss/thumbnail.scss
  src/types.ts
  src/utils/download.ts
Labels: enhancement

#1006 Support executing actions from the query string
  README.md
  src/card.ts
  src/localize/localize.ts
  src/types.ts
  src/utils/action.ts
  src/utils/querystring.ts
Labels: enhancement

#1007 Rename `expand_toggle` action to `expand`
  README.md
  src/card.ts
  src/types.ts
  src/utils/querystring.ts
Labels: refactoring

#1013 Refactor viewer to support other kinds of media players (for non-Frigate media)
  src/components/live/live.ts
  src/components/media-carousel.ts
  src/components/viewer.ts
  src/scss/viewer-carousel.scss
  src/scss/viewer-provider.scss
  src/utils/ha/index.ts
  src/utils/media.ts
Labels: refactoring

#1015 Fix autoplay in media viewer
  src/components/live/live.ts
  src/components/viewer.ts
Labels: bug

#1018 Tolerate numeric unique_ids
  src/camera-manager/frigate/engine-frigate.ts
  src/card.ts
  src/utils/ha/entity-registry/types.ts
Labels: bug

#1019 Tolerate media players not in the entity registry
  src/card.ts
  src/utils/ha/entity-registry/index.ts
Labels: bug

#1022 Add support for MotionEye [Proof of concept for richer support for non-Frigate cameras]
  README.md
  package.json
  src/camera-manager/browse-media/engine-browse-media.ts
  src/camera-manager/browse-media/media.ts
  src/camera-manager/browse-media/types.ts
  src/camera-manager/cache.ts
  src/camera-manager/engine-factory.ts
  src/camera-manager/engine.ts
  src/camera-manager/frigate/assets/frigate-logo-dark.svg
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/frigate/media.ts
  src/camera-manager/frigate/types.ts
  src/camera-manager/generic/engine-generic.ts
  src/camera-manager/manager.ts
  src/camera-manager/motioneye/assets/motioneye-logo.svg
  src/camera-manager/motioneye/engine-motioneye.ts
  src/camera-manager/motioneye/icon.ts
  src/camera-manager/motioneye/types.ts
  src/camera-manager/range.ts
  src/camera-manager/types.ts
  src/camera-manager/util.ts
  src/card.ts
  src/components/gallery.ts
  src/components/live/live.ts
  src/components/media-carousel.ts
  src/components/menu.ts
  src/components/submenu.ts
  src/components/thumbnail.ts
  src/components/timeline-core.ts
  src/components/title-control.ts
  src/components/viewer.ts
  src/const.ts
  src/declarations.d.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/patches/ha-camera-stream.ts
  src/patches/ha-hls-player.ts
  src/scss/gallery.scss
  src/scss/message.scss
  src/scss/thumbnail-feature-event.scss
  src/scss/title-control.scss
  src/scss/viewer-provider.scss
  src/types.ts
  src/utils/basic.ts
  src/utils/download.ts
  src/utils/endpoint.ts
  src/utils/ha/browse-media/browse-media-manager.ts
  src/utils/ha/browse-media/types.ts
  src/utils/ha/entity-registry/types.ts
  src/utils/ha/index.ts
  src/utils/media.ts
  src/utils/thumbnail.ts
  src/view/media.ts
  yarn.lock
Labels: enhancement

#1023 Select camera
  src/components/media-filter.ts
Labels: bug

#1031 Add guide on how to install from artifacts
  README.md
Labels: documentation

#1033 Fix broken show_recordings timeline option
  src/components/timeline-core.ts
  src/utils/timeline-source.ts
Labels: bug

#1034 Improve load performance by dynamically loading engines
  src/camera-manager/engine-factory.ts
  src/camera-manager/manager.ts
Labels: performance

#1036 Add browser support notice
  README.md
Labels: documentation

#1037 Bump version to v5.0.0-beta.1 .
  package.json
Labels: build

#1040 Update language for v5.0.0: `pt-br`
  .vscode/i18n-ally-reviews.yml
  src/localize/languages/pt-BR.json
Labels: enhancement

#1039 Update language for v5.0.0: `it`
  src/localize/languages/it.json
Labels: enhancement
