Repository dermotduffy/advanced-camera-card, pull requests merged in 2024-09, with the labels that each got.

#1512 Move automatic media actions out of carousels
  rollup.config.js
  src/components-lib/media-actions-controller.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/config/types.ts
  src/scss/menu.scss
  src/utils/embla/plugins/auto-media-actions/auto-media-actions.ts
  src/utils/embla/plugins/auto-media-loaded-info/auto-media-loaded-info.ts
  tests/components-lib/media-actions-controller.test.ts
  tests/test-utils.ts
  tests/utils/embla/carousel-controller.test.ts
  tests/utils/embla/plugins/auto-media-actions/auto-media-actions.test.ts
  tests/utils/embla/test-utils.ts
  tests/utils/get-state-obj.test.ts
  vite.config.ts
Labels: refactoring

#1514 Add status bar screenshot
  docs/examples.md
  docs/images/dynamic-status.gif
  docs/screenshots.md
Labels: documentation

#1515 Remove `dev` warnings from docs
  docs/README.md
  docs/_coverpage.md
Labels: documentation

#1516 Bump version to `v6.0.0-beta.1`
  package.json
Labels: build

#1513 Fix overlay z-index for menu
  src/scss/card.scss
Labels: bug

#1517 Improve `fr` translations
  src/localize/languages/fr.json
Labels: documentation

#1518 Add support for arbitrary image entities
  docs/configuration/cameras/README.md
  docs/configuration/cameras/live-provider.md
  docs/configuration/image.md
  src/card-controller/status-bar-item-manager.ts
  src/components/image.ts
  src/components/live/live-image.ts
  src/config/types.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  tests/config/types.test.ts
Labels: enhancement

#1519 Prevent console spam on build
  .yarn/patches/README.md
  .yarn/patches/sass-npm-1.77.4-13b6910aea.patch
  package.json
  yarn.lock
Labels: build

#1520 Add support for `perform-action` calls
  docs/configuration/actions/stock/README.md
  docs/configuration/cameras/README.md
  docs/examples.md
  package.json
  rollup.config.js
  src/components/image.ts
  src/components/submenu.ts
  src/config/management.ts
  src/config/types.ts
  tests/camera-manager/manager.test.ts
  tests/camera-manager/utils/ptz.test.ts
  tests/config/management.test.ts
  tests/config/types.test.ts
  yarn.lock
Labels: enhancement

#1525 fix(docs): Fix broken image URL in docs
  README.md
Labels: documentation

#1526 chore: Update HACS validator to latest
  .github/workflows/release.yml
Labels: build

#1527 fix(docs): Fix typo in override documentation
  docs/configuration/overrides.md
Labels: documentation

#1528 ci: Add initial semantic-release configuration
  .github/workflows/semantic-release.yml
  package.json
  rollup.config.js
  src/card.ts
  src/utils/diagnostics.ts
  tests/utils/diagnostics.test.ts
  yarn.lock
Labels: build

#1529 ci: Install dependencies before semantic-release run
  .github/workflows/build.yml
  .github/workflows/semantic-release.yml
Labels: build

#1530 ci: Fix semantic release credentials
  .github/workflows/semantic-release.yml
Labels: build

#1531 ci: Add write permissions for semantic release jobs
  .github/workflows/semantic-release.yml
Labels: build

#1532 ci: Combine build and release steps
  .github/workflows/semantic-release.yml
Labels: ci

#1536 feat: Add `microphone_disconnect` action
  docs/configuration/actions/custom/README.md
  docs/usage/url-actions.md
  src/card-controller/actions/actions/microphone-disconnect.ts
  src/card-controller/actions/factory.ts
  src/config/types.ts
  tests/card-controller/actions/actions/microphone-disconnect.test.ts
  tests/card-controller/actions/factory.test.ts
Labels: enhancement

#1539 fix: Replace `max_height` with `height`
  docs/configuration/dimensions.md
  src/card-controller/style-manager.ts
  src/config/management.ts
  src/config/types.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/scss/card.scss
  src/scss/gallery.scss
  tests/card-controller/style-manager.test.ts
  tests/config/management.test.ts
  tests/config/types.test.ts
Labels: breaking

#1540 ci: Switch to github actions based semantic PRs
  .github/workflows/semantic-prs.yml
  .github/workflows/semantic-release.yml
Labels: build

#1535 docs: Typo in Profiles configuration page
  docs/configuration/profiles.md
Labels: documentation

#1541 fix: Show the menu even if the view is not yet initialized
  src/card.ts
  src/components-lib/menu-button-controller.ts
  tests/components-lib/menu-button-controller.test.ts
Labels: bug

#1537 feat: Add `microphone_connect` action
  docs/configuration/actions/custom/README.md
  docs/usage/url-actions.md
  src/card-controller/actions/actions/microphone-connect.ts
  src/card-controller/actions/factory.ts
  src/config/types.ts
  tests/card-controller/actions/actions/microphone-connect.test.ts
  tests/card-controller/actions/factory.test.ts
Labels: enhancement

#1545 fix: Fix initialization race condition that occurs in certain circumstances
  src/camera-manager/manager.ts
  src/camera-manager/store.ts
  src/card-controller/card-element-manager.ts
  src/card-controller/config/config-manager.ts
  src/card-controller/default-manager.ts
  src/card-controller/initialization-manager.ts
  src/card-controller/media-player-manager.ts
  src/card-controller/query-string-manager.ts
  src/card-controller/types.ts
  src/card-controller/view/view-manager.ts
  src/card.ts
  src/images/README.md
  src/images/camera-iris.svg
  src/types.ts
  src/utils/ha/index.ts
  src/utils/initializer/initializer.ts
  tests/camera-manager/manager.test.ts
  tests/camera-manager/store.test.ts
  tests/card-controller/config/config-manager.test.ts
  tests/card-controller/default-manager.test.ts
  tests/card-controller/initialization-manager.test.ts
  tests/card-controller/media-player-manager.test.ts
  tests/card-controller/query-string-manager.test.ts
  tests/card-controller/view/view-manager.test.ts
  tests/utils/initializer.test.ts
  vite.config.ts
Labels: bug

#1549 feat: Add loading spinner on card initialization
  docs/configuration/performance.md
  src/card-controller/initialization-manager.ts
  src/card.ts
  src/components/loading.ts
  src/scss/card.scss
  src/scss/loading.scss
  tests/card-controller/initialization-manager.test.ts
Labels: enhancement

#1550 feat: Show diagnostics in yaml instead of json
  .github/ISSUE_TEMPLATE/bug_report.md
  package.json
  src/components/diagnostics.ts
  src/components/message.ts
  src/scss/message.scss
  yarn.lock
Labels: enhancement

#1552 fix: Assume conditions are `state` conditions unless otherwise specified
  src/card-controller/conditions-manager.ts
  src/config/types.ts
  tests/card-controller/conditions-manager.test.ts
Labels: bug

#1553 fix: Menu linear gradient is the wrong direction on left/right menus
  src/components/gallery.ts
  src/scss/menu.scss
Labels: bug

#1555 fix: Timeline window should match selected events for media views
  src/card-controller/view/factory.ts
  tests/card-controller/view/factory.test.ts
Labels: bug

#1558 fix: Configured PTZ actions should overrule auto-detected actions (not merge with them)
  docs/configuration/cameras/README.md
  src/camera-manager/frigate/camera.ts
  src/camera-manager/utils/ptz.ts
  tests/camera-manager/frigate/camera.test.ts
  tests/camera-manager/utils/ptz.test.ts
  tests/utils/ptz.test.ts
Labels: bug

#1565 fix: Use pkg version until semantic-release is used
  rollup.config.js
  src/utils/diagnostics.ts
Labels: bug

#1569 perf: Only trigger a state change if the state is definitely different
  src/card-controller/conditions-manager.ts
  tests/card-controller/conditions-manager.test.ts
Labels: performance

#1570 fix: Unparseable config when using the `low-performance` profile
  src/card-controller/conditions-manager.ts
  src/card-controller/config/config-manager.ts
  src/card-controller/default-manager.ts
  src/card-controller/status-bar-item-manager.ts
  src/components-lib/status-bar-controller.ts
  src/components/live/live.ts
  src/components/message.ts
  src/config/profiles/low-performance.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/scss/message.scss
  tests/card-controller/conditions-manager.test.ts
  tests/card-controller/config/config-manager.test.ts
  tests/config/profiles/low-performance.test.ts
  tests/config/profiles/scrubbing.test.ts
  tests/test-utils.ts
Labels: bug

#1571 fix: Untriggering to default should reset to default camera
  src/card-controller/view/factory.ts
  tests/card-controller/view/factory.test.ts
Labels: bug

#1572 fix: Weird menu rendering placement issue on Firefox browsers
  src/scss/overlay.scss
Labels: bug

#1573 chore: Bump version to `v6.0.0-beta.3`
  package.json
Labels: chore

#1574 ci: Update labels for release drafter
  .github/release-drafter.yml
Labels: ci

#1576 fix: Don't block for microphone initialization if browser does not support it
  src/card-controller/initialization-manager.ts
  src/card-controller/microphone-manager.ts
  src/components-lib/menu-button-controller.ts
  tests/card-controller/initialization-manager.test.ts
  tests/card-controller/microphone-manager.test.ts
  tests/components-lib/menu-button-controller.test.ts
Labels: bug

#1575 feat: Add new `casting` profile
  docs/configuration/profiles.md
  src/config/profiles/casting.ts
  src/config/profiles/index.ts
  src/config/types.ts
  src/editor.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  tests/config/profiles/casting.test.ts
Labels: feature

#1579 fix: Don't run the query string actions until after initialization
  src/card-controller/card-element-manager.ts
  src/card-controller/query-string-manager.ts
  src/card-controller/view/view-manager.ts
  src/card.ts
  tests/card-controller/initialization-manager.test.ts
  tests/card-controller/query-string-manager.test.ts
  tests/card-controller/view/view-manager.test.ts
Labels: bug

#1584 fix: Menu linear background should match alignment
  src/scss/menu.scss
Labels: bug

#1585 fix: Multiple cards should form a masonry layout
  src/card-controller/card-element-manager.ts
  src/card.ts
  tests/card-controller/card-element-manager.test.ts
Labels: bug

#1587 fix: Ensure media info is dispatched after view change
  src/utils/embla/carousel-controller.ts
  src/utils/embla/plugins/auto-media-loaded-info/auto-media-loaded-info.ts
  tests/utils/embla/carousel-controller.test.ts
  tests/utils/embla/plugins/auto-media-loaded-info/auto-media-loaded-info.test.ts
Labels: bug

#1589 fix: Menu should extend beyond card boundary
  src/scss/card.scss
  src/scss/drawer-inject.scss
Labels: bug

#1590 fix: Don't hide menu in casting profile
  docs/usage/casting.md
  src/config/profiles/casting.ts
  tests/config/profiles/casting.test.ts
Labels: bug

#1591 chore: Bump version to `v6.0.0-beta.4`
  package.json
Labels: chore

#1592 docs: Add information on the new release philosophy
  docs/README.md
  docs/developing.md
  docs/rolling-back.md
Labels: documentation

#1593 chore: Remove superfluous votes needed label
  .github/labels.yml
Labels: chore

#1595 fix: Fix curved corners (again)
  src/card.ts
  src/scss/card.scss
  src/scss/overlay.scss
Labels: bug

#1596 chore: Bump version to `v6.0.0-beta.5`
  package.json
Labels: chore

#1597 refactor: Refactor entity register manager
  src/camera-manager/browse-media/camera.ts
  src/camera-manager/browse-media/engine-browse-media.ts
  src/camera-manager/engine-factory.ts
  src/camera-manager/frigate/camera.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/card-controller/controller.ts
  src/card-controller/media-player-manager.ts
  src/card-controller/types.ts
  src/components/menu.ts
  src/components/submenu.ts
  src/utils/diagnostics.ts
  src/utils/ha/entity-state-translation.ts
  src/utils/ha/registry/cache.ts
  src/utils/ha/registry/device/index.ts
  src/utils/ha/registry/device/types.ts
  src/utils/ha/registry/entity/index.ts
  src/utils/ha/registry/entity/types.ts
  tests/camera-manager/browse-media/camera.test.ts
  tests/camera-manager/engine-factory.test.ts
  tests/camera-manager/frigate/camera.test.ts
  tests/camera-manager/store.test.ts
  tests/card-controller/controller.test.ts
  tests/card-controller/media-player-manager.test.ts
  tests/test-utils.ts
  tests/utils/diagnostics.test.ts
  tests/utils/ha/registry/cache.test.ts
  tests/utils/ha/registry/entity/index.test.ts
  vite.config.ts
Labels: refactoring

#1598 refactor: Cache device information centrally
  src/camera-manager/manager.ts
  src/card-controller/controller.ts
  src/card.ts
  src/components/diagnostics.ts
  src/components/views.ts
  src/utils/diagnostics.ts
  src/utils/ha/registry/device/index.ts
  src/utils/ha/registry/entity/index.ts
  tests/card-controller/controller.test.ts
  tests/test-utils.ts
  tests/utils/diagnostics.test.ts
  tests/utils/ha/registry/device/index.test.ts
  tests/utils/ha/registry/entity/index.test.ts
  vite.config.ts
Labels: refactoring
