Repository dermotduffy/advanced-camera-card, pull requests merged in 2024-10, with the labels that each got.

#1601 fix: Fix card initialization on some cast devices
  src/utils/ha/index.ts
Labels: bug

#1602 feat: Rework casting profile and documentation
  docs/usage/casting.md
  src/config/profiles/casting.ts
  src/const.ts
  tests/config/profiles/casting.test.ts
Labels: feature

#1605 fix: `media_stop` not supported on Google Cast devices
  src/card-controller/media-player-manager.ts
  src/const.ts
  tests/card-controller/media-player-manager.test.ts
Labels: bug

#1606 fix: Fix thumbnail carousel scroll position
  package.json
  src/components/thumbnail-carousel.ts
  src/utils/embla/carousel-controller.ts
  src/utils/embla/plugins/auto-size/auto-size.ts
  tests/utils/embla/carousel-controller.test.ts
  tests/utils/embla/plugins/auto-size/auto-size.test.ts
  yarn.lock
Labels: bug

#1607 chore: Automatically lock closed issues and PRs
  .github/workflows/lock.yml
Labels: chore

#1611 chore: Add lock debugging
  .github/workflows/lock.yml
Labels: chore

#1615 docs: Add examples of entity-less cameras
  docs/examples.md
Labels: documentation

#1616 fix: Do not show the cameras menu with <= 1 camera
  src/components-lib/menu-button-controller.ts
  tests/components-lib/menu-button-controller.test.ts
Labels: bug

#1617 fix: Do not show menu icons on top of other unrelated HA content
  src/scss/card.scss
Labels: bug

#1619 fix: Only show PTZ controls for selected camera in grid mode
  src/components/live/live.ts
  src/utils/substream.ts
  tests/utils/substream.test.ts
Labels: bug

#1620 fix: Update `go2rtc` client with the latest changes
  src/components/live/go2rtc/video-rtc.js
Labels: bug

#1622 fix: Show a background image in case media doesn't load
  src/card-controller/card-element-manager.ts
  src/card-controller/style-manager.ts
  src/card-controller/types.ts
  src/scss/image.scss
  src/scss/live-provider.scss
  src/scss/media-background.scss
  src/scss/viewer-provider.scss
  tests/card-controller/card-element-manager.test.ts
  tests/card-controller/style-manager.test.ts
Labels: bug

#1623 fix: Treat a un/selection of grid items as `selected` for auto media actions
  docs/configuration/live.md
  docs/configuration/media-viewer.md
  src/components-lib/media-actions-controller.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/utils/ha/registry/device/types.ts
  tests/components-lib/media-actions-controller.test.ts
Labels: bug

#1624 fix: Zoom/pan support for WebRTC Card
  docs/configuration/cameras/live-provider.md
  src/components/live/live-webrtc-card.ts
Labels: bug

#1625 chore: Bump version to `6.0.0-beta.6`
  package.json
Labels: chore

#1627 fix: Always play the media target after a HA tab change
  src/components/live/live.ts
Labels: bug

#1631 fix: Correctly determine whether to show PTZ controls
  src/components/live/live.ts
Labels: bug

#1635 fix: Improve media background image
  src/card-controller/card-element-manager.ts
  src/card-controller/style-manager.ts
  src/card-controller/types.ts
  src/card.ts
  src/components/loading.ts
  src/images/camera-iris-transparent.svg
  src/scss/loading.scss
  src/scss/media-background.scss
  tests/card-controller/card-element-manager.test.ts
  tests/card-controller/style-manager.test.ts
Labels: bug

#1636 feat: Add `permanent` menu items for hidden menus
  docs/configuration/elements/custom/README.md
  docs/configuration/menu.md
  src/card-controller/actions/factory.ts
  src/components-lib/menu-button-controller.ts
  src/components-lib/menu-controller.ts
  src/config/types.ts
  src/editor.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  tests/components-lib/menu-button-controller.test.ts
  tests/components-lib/menu-controller.test.ts
Labels: feature

#1639 fix: Rationalize custom icons to avoid duplication
  docs/_coverpage.md
  docs/configuration/elements/custom/README.md
  docs/configuration/menu.md
  docs/images/icons/frigate.svg
  docs/images/icons/motioneye.svg
  docs/index.html
  docs/usage/README.md
  docs/usage/_sidebar.md
  docs/usage/custom-icons.md
  scripts/docs-update-icons.sh
  src/camera-manager/frigate/assets/frigate-logo-dark.svg
  src/camera-manager/frigate/assets/frigate.svg
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/frigate/icon.ts
  src/camera-manager/motioneye/assets/motioneye.svg
  src/camera-manager/motioneye/engine-motioneye.ts
  src/camera-manager/motioneye/icon.ts
  src/components-lib/menu-controller.ts
  src/components/menu.ts
  src/components/status-bar.ts
  src/components/submenu.ts
  src/editor.ts
  src/scss/editor.scss
  src/utils/custom-icons.ts
  src/utils/ha/index.ts
  tests/components-lib/menu-controller.test.ts
  tests/utils/custom-icons.test.ts
  tsconfig.json
  vite.config.ts
Labels: bug

#1640 docs: Fix incorrect `change_zoom` example
  docs/configuration/actions/custom/README.md
  docs/examples.md
Labels: documentation

#1641 chore: Bump version to `v6.0.0-beta.8`
  package.json
Labels: chore

#1642 docs: Fix PTZ example
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  docs/configuration/actions/stock/README.md
  docs/examples.md
Labels: documentation

#1644 refactor: Split `live.ts` into multiple files
  .github/ISSUE_TEMPLATE/bug_report.md
  src/components-lib/live/utils/get-technology-for-video-rtc.ts
  src/components/image.ts
  src/components/live/carousel.ts
  src/components/live/grid.ts
  src/components/live/index.ts
  src/components/live/live.ts
  src/components/live/provider.ts
  src/components/live/providers/go2rtc/README.md
  src/components/live/providers/go2rtc/index.ts
  src/components/live/providers/go2rtc/video-rtc.d.ts
  src/components/live/providers/go2rtc/video-rtc.js
  src/components/live/providers/ha.ts
  src/components/live/providers/image.ts
  src/components/live/providers/jsmpeg.ts
  src/components/live/providers/webrtc-card.ts
  src/components/views.ts
  tests/components-lib/live/utils/get-technology-for-video-rts.test.ts
Labels: refactoring

#1645 refactor: Split `viewer.ts` into multiple files
  src/components/live/carousel.ts
  src/components/viewer.ts
  src/components/viewer/carousel.ts
  src/components/viewer/grid.ts
  src/components/viewer/index.ts
  src/components/viewer/provider.ts
  src/components/views.ts
Labels: refactoring
