Repository dermotduffy/advanced-camera-card, pull requests merged in 2024-06, with the labels that each got.

#1462 Update date-fns and date-fns-tz to v3
  package.json
  rollup.config.js
  src/camera-manager/browse-media/media.ts
  src/camera-manager/frigate/engine-frigate.ts
  src/camera-manager/frigate/media.ts
  src/camera-manager/frigate/util.ts
  src/camera-manager/manager.ts
  src/camera-manager/motioneye/engine-motioneye.ts
  src/camera-manager/utils/range-to-cache-friendly.ts
  src/components-lib/live/live-controller.ts
  src/components-lib/media-filter-controller.ts
  src/components-lib/timeline-source.ts
  src/components/thumbnail.ts
  src/components/timeline-core.ts
  src/utils/basic.ts
  src/utils/ha/browse-media/browse-media-manager.ts
  src/utils/screenshot.ts
  tests/camera-manager/cache.test.ts
  tests/camera-manager/frigate/util.test.ts
  tests/camera-manager/manager.test.ts
  tests/camera-manager/range.test.ts
  tests/card-controller/auto-update-manager.test.ts
  tests/card-controller/interaction-manager.test.ts
  tests/card-controller/triggers-manager.test.ts
  tests/components-lib/media-filter-controller.test.ts
  tests/utils/embla/plugins/auto-media-actions/auto-media-actions.test.ts
  tests/utils/media-to-view.test.ts
  yarn.lock
Labels: build

#1452 Update Node.js from 18 to 20 LTS
  package.json
Labels: build

#1463 Update typescript to v5
  package.json
  src/action-handler-directive.ts
  src/components/live/live-ha.ts
  yarn.lock
Labels: build

#1470 Convert docs dependencies to be locally served
  docs/css/theme-simple-dark.css
  docs/css/theme-simple.css
  docs/index.html
  docs/js/docsify-copy-code.min.js
  docs/js/docsify-sidebar-collapse.min.js
  docs/js/docsify-themeable.min.js
  docs/js/docsify.min.js
  docs/js/gtag.min.js
  docs/js/prism-yaml.min.js
  docs/js/search.js
  docs/js/zoom-image.min.js
  package.json
  scripts/docs-update-dependencies.sh
  scripts/docs-update-images.sh
Labels: documentation

#1464 Update all non-major dependencies
  package.json
  yarn.lock
Labels: dependencies

#1474 Update rollup to v3 and its plugins
  package.json
  rollup.config.js
  yarn.lock
Labels: dependencies
