Repository dermotduffy/advanced-camera-card, pull requests merged in 2024-12, with the labels that each got.

#1702 perf: Change media fetches to be asynchronous to view render
  src/camera-manager/manager.ts
  src/card-controller/view/factory.ts
  src/card-controller/view/modifiers/index.ts
  src/card-controller/view/modifiers/set-query.ts
  src/card-controller/view/query-executor.ts
  src/card-controller/view/types.ts
  src/card-controller/view/view-manager.ts
  src/card-controller/view/view-query-executor.ts
  src/components/gallery.ts
  src/components/viewer/index.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/utils/diagnostics.ts
  src/view/view.ts
  tests/card-controller/view/factory.test.ts
  tests/card-controller/view/modifiers/index.test.ts
  tests/card-controller/view/modifiers/set-query.test.ts
  tests/card-controller/view/view-manager.test.ts
  tests/card-controller/view/view-query-executor.test.ts
Labels: performance

#1705 fix: Allow `9:16` aspect-ratio gallery to render without a gap in Safari
  src/scss/gallery.scss
Labels: bug

#1706 chore: Bump version to `v6.0.0-beta.9`
  package.json
Labels: chore

#1703 feat: Increase max thumbnail size to `300px`
  docs/configuration/cameras/engine.md
  docs/configuration/live.md
  docs/configuration/media-gallery.md
  docs/configuration/media-viewer.md
  docs/configuration/timeline.md
  src/components/gallery.ts
  src/config/types.ts
  src/scss/const.scss
  src/scss/thumbnail-details.scss
  src/scss/thumbnail-feature-thumbnail.scss
Labels: feature

#1713 docs: Remove use of `ms-high-contrast`
  docs/css/theme-simple-dark.css
  docs/css/theme-simple.css
Labels: documentation

#1716 chore: Bump version to `v6.0.0`
  package.json
Labels: chore

#1717 chore: Set package version back to `0.0.0-dev` to prepare for semantic release
  package.json
Labels: chore

#1718 fix: Change for semantic-release testing
  src/card.ts
Labels: bug

#1719 ci: Allow semantic release to create draft releases
  .github/workflows/semantic-release.yml
  package.json
Labels: ci

#1724 ci: Adjust semantic release settings closer to prior releases
  package.json
  yarn.lock
Labels: ci

#1725 ci: Use correct release name variable
  package.json
Labels: ci

#1726 ci: Convert old release workflows to manual only
  .github/workflows/manual-release-drafter.yml
  .github/workflows/manual-release.yml
Labels: ci

#1728 ci: Enable semantic releases
  package.json
Labels: ci

#1731 fix: Fix `hover-card` menu style
  src/scss/card.scss
Labels: bug

#1734 fix: Correctly display MJPEG streams
  src/patches/ha-camera-stream.ts
Labels: bug

#1738 fix: Panel mode should exclude header height
  docs/configuration/dimensions.md
  src/scss/card.scss
Labels: bug

#1747 fix: Only fetch Reolink media for cameras that support it
  src/camera-manager/browse-media/engine-browse-media.ts
  src/camera-manager/reolink/engine-reolink.ts
  src/camera-manager/reolink/types.ts
  src/utils/ha/browse-media/browse-media-manager.ts
  tests/camera-manager/reolink/engine-reolink.test.ts
Labels: bug

#1750 fix: Panel height should be 100% when casted
  src/card-controller/card-element-manager.ts
  src/components-lib/menu-button-controller.ts
  src/scss/card.scss
  src/utils/casting.ts
  tests/card-controller/card-element-manager.test.ts
  tests/utils/casting.test.ts
  vite.config.ts
Labels: bug

#1752 fix: Update French translations
  src/localize/languages/fr.json
Labels: bug

#1756 refactor: Rename classes internally to better support `rtl` languages
  src/components/next-prev-control.ts
  src/scss/next-previous-control.scss
Labels: refactoring

#1757 fix: Render media correctly in `rtl` languages
  src/components/carousel.ts
  src/components/live/carousel.ts
  src/components/next-prev-control.ts
  src/components/viewer/carousel.ts
  src/scss/next-previous-control.scss
  src/utils/embla/carousel-controller.ts
  src/utils/text-direction.ts
  tests/utils/embla/carousel-controller.test.ts
  tests/utils/text-direction.test.ts
  vite.config.ts
Labels: bug

#1759 fix: Fix builtin controls showing up when they should not
  src/components/live/providers/ha.ts
Labels: bug

#1760 fix: Fix issue where wrong `ha` stream may be referred to [skip ci]
  src/patches/ha-camera-stream.ts
Labels: bug

#1764 fix: Substantially reduce cases where errors block whole card
  src/components-lib/live/live-controller.ts
  src/components-lib/live/utils/dispatch-live-error.ts
  src/components/image.ts
  src/components/live/index.ts
  src/components/live/provider.ts
  src/components/live/providers/go2rtc/index.ts
  src/components/live/providers/ha.ts
  src/components/live/providers/image.ts
  src/components/live/providers/jsmpeg.ts
  src/components/live/providers/webrtc-card.ts
  src/components/message.ts
  src/components/next-prev-control.ts
  src/components/thumbnail.ts
  src/components/viewer/carousel.ts
  src/const.ts
  src/patches/ha-hls-player.ts
  src/patches/ha-web-rtc-player.ts
  src/utils/endpoint.ts
  src/utils/get-state-obj.ts
  src/utils/task.ts
  src/utils/thumbnail.ts
  tests/components-lib/live/live-controller.test.ts
  tests/components-lib/live/utils/dispatch-live-error.test.ts
  tests/utils/endpoint.test.ts
  tests/utils/get-state-obj.test.ts
Labels: bug

#1765 fix: Only include custom integrations in diagnostics
  src/utils/diagnostics.ts
  tests/utils/diagnostics.test.ts
Labels: bug

#1766 fix: Fix certain `webrtc` streams that were not loading correctly
  src/patches/ha-web-rtc-player.ts
Labels: bug

#1767 fix: default action should fetch new media
  src/card-controller/actions/actions/default.ts
  src/card-controller/actions/actions/view.ts
  tests/card-controller/actions/actions/default.test.ts
Labels: bug

#1768 fix: Allow `submenus` to overflow the menu in all cases
  src/scss/menu.scss
Labels: bug

#1770 feat: Add new option to always error on entity `unavailable`
  docs/configuration/cameras/README.md
  src/components/live/provider.ts
  src/config/types.ts
  tests/config/types.test.ts
Labels: feature

#1771 docs: Add a new page for common support answers
  docs/support.md
Labels: documentation

#1791 fix: Always fetch media for "most recent media" views
  src/card-controller/view/view-query-executor.ts
  tests/card-controller/view/view-query-executor.test.ts
Labels: bug

#1794 fix: Allow icon styles to be overridden
  src/components/icon.ts
  src/components/menu.ts
  src/components/submenu.ts
  src/types.ts
Labels: bug
