Repository dermotduffy/advanced-camera-card, pull requests merged in 2024-03, with the labels that each got.

#1391 Prevent test coverage backsliding for 100% coverage files
  vite.config.ts
Labels: testing

#1392 Remove remnants of old PTZ `auto` mode
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
Labels: bug

#1394 Adapt dimensions and media layout options to be per camera
  README.md
  src/card-controller/style-manager.ts
  src/card.ts
  src/components/elements.ts
  src/components/image.ts
  src/components/live/live.ts
  src/components/viewer.ts
  src/config-mgmt.ts
  src/config/types.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/scss/live-carousel.scss
  src/scss/live-provider.scss
  src/utils/basic.ts
  tests/card-controller/style-manager.test.ts
  tests/config-mgmt.test.ts
  tests/utils/basic.test.ts
  vite.config.ts
Labels: enhancement

#1395 Always render a view even if default is unsupported
  src/camera-manager/frigate/camera.ts
  src/camera-manager/store.ts
  src/card-controller/initialization-manager.ts
  src/card-controller/view-manager.ts
  tests/camera-manager/frigate/camera.test.ts
  tests/camera-manager/store.test.ts
  tests/card-controller/view-manager.test.ts
Labels: bug

#1396 Ensure timeline menu button shows up when it should
  src/card-controller/actions-manager.ts
  src/card-controller/view-manager.ts
  src/card.ts
  src/components-lib/menu-button-controller.ts
  tests/card-controller/actions-manager.test.ts
  tests/card-controller/view-manager.test.ts
  tests/components-lib/menu-button-controller.test.ts
Labels: bug

#1398 Add support for `user` and `numeric_state` conditions
  README.md
  src/card-controller/automations-manager.ts
  src/card-controller/conditions-manager.ts
  src/card-controller/hass-manager.ts
  src/card.ts
  src/config-mgmt.ts
  src/config/types.ts
  src/const.ts
  tests/card-controller/automations-manager.test.ts
  tests/card-controller/conditions-manager.test.ts
  tests/card-controller/hass-manager.test.ts
  tests/config-mgmt.test.ts
  tests/config/types.test.ts
  tests/test-utils.ts
Labels: enhancement, breaking

#1399 Add ability to set timeline pan mode via config
  README.md
  src/components/timeline-core.ts
  src/config/types.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/en.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  tests/config/types.test.ts
  vite.config.ts
Labels: enhancement

#1409 Add Catalan translations
  project.inlang.json
  src/localize/languages/ca.json
  src/localize/localize.ts
Labels: enhancement

#1417 Add French language translations
  project.inlang.json
  project.inlang/project_id
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  src/localize/localize.ts
Labels: enhancement

#1418 Add support for configuration profiles
  src/card-controller/conditions-manager.ts
  src/card-controller/config-manager.ts
  src/card-controller/style-manager.ts
  src/components/live/live.ts
  src/config/management.ts
  src/config/profiles/index.ts
  src/config/profiles/low-performance.ts
  src/config/profiles/scrubbing.ts
  src/config/types.ts
  src/const.ts
  src/editor.ts
  src/localize/languages/ca.json
  src/localize/languages/en.json
  src/localize/languages/fr.json
  src/localize/languages/it.json
  src/localize/languages/pt-BR.json
  src/localize/languages/pt-PT.json
  tests/card-controller/config-manager.test.ts
  tests/card-controller/style-manager.test.ts
  tests/config/management.test.ts
  tests/config/profiles/index.test.ts
  tests/config/profiles/low-performance.test.ts
  tests/config/profiles/scrubbing.test.ts
  tests/config/types.test.ts
  vite.config.ts
Labels: enhancement
