Repository dermotduffy/advanced-camera-card, pull requests merged in 2025-05, with the labels that each got.

#2052 docs: Add folders screenshot
  docs/images/folders.png
  docs/screenshots.md
Labels: documentation

#2030 fix: Improve French translations
  src/localize/languages/fr.json
Labels: bug

#2053 chore: Update yarn lockfile
  yarn.lock
Labels: chore

#2059 fix: Download icon should show on thumbnails
  src/components/thumbnail-carousel.ts
Labels: bug

#2063 fix: Allow multiple overrides to operate independently
  src/card-controller/config/config-manager.ts
  src/card-controller/config/get-overridden-config.ts
  src/card-controller/config/overrides-manager.ts
  src/config/schema/overrides.ts
  tests/card-controller/config/config-manager.test.ts
  tests/card-controller/config/get-overridden-config.test.ts
  tests/card-controller/config/overrides-manager.test.ts
Labels: bug

#2071 feat: Add `or` and `template` folder media matchers
  docs/configuration/_sidebar.md
  docs/configuration/actions/_sidebar.md
  docs/configuration/actions/custom/_sidebar.md
  docs/configuration/actions/stock/_sidebar.md
  docs/configuration/actions/templates.md
  docs/configuration/cameras/_sidebar.md
  docs/configuration/elements/_sidebar.md
  docs/configuration/elements/custom/_sidebar.md
  docs/configuration/elements/stock/_sidebar.md
  docs/configuration/folders.md
  docs/configuration/templates.md
  docs/examples.md
  src/card-controller/folders/executor.ts
  src/card-controller/folders/ha/engine.ts
  src/card-controller/folders/ha/media-matcher.ts
  src/card-controller/folders/manager.ts
  src/card-controller/folders/types.ts
  src/card-controller/templates/index.ts
  src/card-controller/view/query-executor.ts
  src/config/schema/folders.ts
  tests/card-controller/folders/executor.test.ts
  tests/card-controller/folders/ha/engine.test.ts
  tests/card-controller/folders/ha/media-matcher.test.ts
  tests/card-controller/folders/manager.test.ts
  tests/config/schema/folders.test.ts
Labels: feature

#2074 feat: Allow matching of folders based on parsed date
  docs/configuration/folders.md
  docs/examples.md
  src/card-controller/folders/ha/engine.ts
  src/card-controller/folders/ha/media-matcher.ts
  src/config/schema/folders.ts
  tests/card-controller/folders/ha/media-matcher.test.ts
Labels: feature

#2076 docs: Remove references to card rename process
  docs/README.md
  docs/common/rename-hacs.md
  docs/configuration/folders.md
  docs/rolling-back.md
Labels: documentation
